Repository OWASP/Python-Honeypot, pull requests merged in 2020-07, with the labels that each got.

#93 Test API and database I/O
  database/connector.py
  tests/test_api.py
  tests/test_connector.py
Labels: GSOC

#101 Test core functionality
  tests/test_core_alert.py
  tests/test_core_compatible.py
  tests/test_core_get_modules.py
Labels: GSOC

#108 tshark starter bug fixed
  core/network.py
Labels: bug, priority

#109 fixing the message format which had slashes.
  core/load.py
Labels: GSOC, bug

#110 fix logo and error message for mongodb in api server.
  core/alert.py
  core/compatible.py
Labels: GSOC, bug
