Repository OWASP/Python-Honeypot, pull requests merged in 2020-08, with the labels that each got.

#115 Update contributing.md
  .github/workflows/python-app.yml
  CONTRIBUTING.md
Labels: ready for review

#119 fix tmp thread naming.
  .github/workflows/python-app.yml
  core/compatible.py
Labels: GSOC, ready for review

#120 fix bug in generate token.
  core/compatible.py
  tests/test_core_compatible.py
Labels: GSOC, ready for review

#103 Replace tshark with pyshark library
  .github/workflows/python-app.yml
  config.py
  core/compatible.py
  core/load.py
  core/network.py
  database/connector.py
  database/datatypes.py
  requirements.txt
  tests/test_connector.py
Labels: GSOC, priority, ready for review

#48 added file watcher script for weak ftp/ssh strategy and changed dockerfile
  core/file_monitor.py
  database/connector.py
  database/datatypes.py
  modules/ftp/weak_password/Dockerfile
  modules/ftp/weak_password/__init__.py
  modules/ssh/weak_password/__init__.py
  requirements.txt
Labels: GSOC, priority, ready for review

#75 Dockerfile
  .github/workflows/python-app.yml
  .gitignore
  Dockerfile.api
  config.py
  core/compatible.py
  core/load.py
  core/network.py
  database/connector.py
  database/datatypes.py
  docker-compose-host.yml
  docker-compose.yml
  readme.md
  requirements.txt
  tests/test_connector.py
  tests/test_core_compatible.py
Labels: GSOC, priority, ready for review

#100 Log explorer
  api/server.py
  web/static/css/bootstrap.min.css
  web/static/css/bootstrap.min.css.map
  web/static/css/buttons.dataTables.min.css
  web/static/css/jquery.dataTables.css
  web/static/css/materialize.min.css
  web/static/css/style.css
  web/static/font/roboto/Roboto-Bold.ttf
  web/static/font/roboto/Roboto-Bold.woff
  web/static/font/roboto/Roboto-Bold.woff2
  web/static/font/roboto/Roboto-Regular.ttf
  web/static/font/roboto/Roboto-Regular.woff
  web/static/font/roboto/Roboto-Regular.woff2
  web/static/font/roboto/Roboto-Thin.ttf
  web/static/font/roboto/Roboto-Thin.woff
  web/static/font/roboto/Roboto-Thin.woff2
  web/static/img/sort_asc.png
  web/static/img/sort_asc_disabled.png
  web/static/img/sort_both.png
  web/static/img/sort_desc.png
  web/static/img/sort_desc_disabled.png
  web/static/index.html
  web/static/js/bootstrap.min.js
  web/static/js/bootstrap.min.js.map
  web/static/js/buttons.html5.min.js
  web/static/js/dataTables.buttons.min.js
  web/static/js/explore.js
  web/static/js/jquery.dataTables.min.js
  web/static/js/jszip.min.js
  web/static/js/main.js
  web/static/js/materialize.min.js
Labels: GSOC, priority, ready for review

#111 added logging functions in core.log
  config.py
  core/alert.py
  core/log.py
Labels: GSOC, priority, ready for review

#129 Fix bug in docker-compose-host file
  .github/workflows/python-app.yml
  config.py
  docker-compose-host-ci.yml
  docker-compose-host.yml
Labels: GSOC

#136 clean and fixes
  .flake8
  .github/workflows/python-app.yml
  .owasp_honeypot
  api/server.py
  api/utility.py
  config.py
  core/alert.py
  core/color.py
  core/compatible.py
  core/exit_helper.py
  core/file_monitor.py
  core/get_modules.py
  core/load.py
  core/log.py
  core/network.py
  database/connector.py
  lib/argparse/__init__.py
  lib/argparse/readme.md
  lib/argparse/v2/__init__.py
  lib/argparse/v2/argparse.py
  lib/argparse/v3/__init__.py
  lib/argparse/v3/argparse.py
  lib/ip2location/IP2Location.py
  lib/language/__init__.py
  lib/language/messages_en.py
  modules/ftp/weak_password/__init__.py
  modules/http/basic_auth_strong_password/__init__.py
  modules/ics/veeder_root_guardian_ast/Dockerfile
  modules/ics/veeder_root_guardian_ast/files/commands.py
  modules/ics/veeder_root_guardian_ast/files/veeder_root_guardian_ast_service.py
  modules/ssh/weak_password/__init__.py
  requirements.txt
  tests/test_api.py
  tests/test_core_alert.py
  tests/test_core_compatible.py
  tests/test_core_get_modules.py
Labels: GSOC, ready for review

#98 added a new SMTP module.
  .flake8
  modules/smtp/__init__.py
  modules/smtp/strong_password/Dockerfile
  modules/smtp/strong_password/__init__.py
  modules/smtp/strong_password/files/smtpd_server/readme.md
  modules/smtp/strong_password/files/smtpd_server/secure_smtpd/__init__.py
  modules/smtp/strong_password/files/smtpd_server/secure_smtpd/config/__init__.py
  modules/smtp/strong_password/files/smtpd_server/secure_smtpd/config/log.py
  modules/smtp/strong_password/files/smtpd_server/secure_smtpd/process_pool.py
  modules/smtp/strong_password/files/smtpd_server/secure_smtpd/smtp_channel.py
  modules/smtp/strong_password/files/smtpd_server/secure_smtpd/smtp_server.py
  modules/smtp/strong_password/files/smtpd_server/smtp_honeypot.py
  tests/test_api.py
  tests/test_connector.py
  tests/test_core_get_modules.py
Labels: GSOC, ready for review

#123 Oraganize .pcap files.
  .github/workflows/python-app.yml
  .gitignore
  api/server.py
  config.py
  core/load.py
  core/network.py
  database/connector.py
  database/datatypes.py
  pcapfiles/readme.md
  web/static/css/dataTables.checkboxes.css
  web/static/css/datatables.min.css
  web/static/css/style.css
  web/static/index.html
  web/static/js/Chart.min.js
  web/static/js/dataTables.checkboxes.min.js
  web/static/js/datatables.min.js
  web/static/js/explore.js
Labels: GSOC, priority, ready for review
