Repository OWASP/Python-Honeypot, pull requests merged in 2020-09, with the labels that each got.

#170 enhance webui
  web/static/index.html
  web/static/js/main.js
Labels: enhancement

#163 Development
  .github/workflows/ci.yml
  .github/workflows/shiftleft.yml
  modules/ics/veeder_root_guardian_ast/Dockerfile
  modules/ics/veeder_root_guardian_ast/__init__.py
  modules/ics/veeder_root_guardian_ast/files/config.py
  modules/ics/veeder_root_guardian_ast/files/veeder_root_guardian_ast_service.py
  requirements.txt
  web/static/index.html
  web/static/js/explore.js
  web/static/js/main.js
Labels: security findings

#173 online/api search instead of offline cache - fix for #168
  api/database_queries.py
  api/server.py
  api/utility.py
  database/datatypes.py
  web/static/js/explore.js
Labels: ready for review

#117 added instructions for adding the modules.
  CONTRIBUTING.md
  core/load.py
  core/log.py
  core/network.py
  database/connector.py
  database/datatypes.py
  readme.md
Labels: GSOC
